services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: yessir
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    image: this-and-that-dev
    ports:
    - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
