services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: yessir
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: this-and-that-dev
    ports:
    - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
